project:
  type: website
  output-dir: docs

website:
  title: "Elvis Elli"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
        - text: Projects
        - text: Publications
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

