project:
  type: website
  output-dir: docs
  preview:
    browser: true
    
website:
  #title: "Elvis Elli"
  page-footer: 
    right: "This Website was created by Elvis F. Elli with [Quarto](https://quarto.org/)"
  navbar:
    left: 
      - text: Home
        href: index.qmd
    right:
      - text: Team
        href: Team/about.qmd
      - text: Projects
        href: Projects/about.qmd
      - text: Publications
        href: Publications/about.qmd
      - icon: github
        href: https://github.com/ElvisElli
      - icon: twitter
        href: https://twitter.com/Elli_EF
format:
  html:
    theme: flatly
    css: styles.css
editor: visual

