project:
  type: website
  preview:
    browser: true
    
website:
  title: "Elvis Elli"
  navbar:
    right:
      #- about.qmd
      - icon: github
        href: https://github.com/ElvisElli
      - icon: twitter
        href: https://twitter.com/Elli_EF
      - text: Projects
        href: Projects/about.qmd
      - text: Publications
        href: Publications/about.qmd
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

